### ISSUE TITLE
Error at restrictedobjects/code/extensions/Restrictable.php line 305

### ISSUE THREAD

**Issue by Clustmart** [silverstripe-australia/silversocial#1]
The complete error message, as stored in file:///var/www/sites/silversocial/wwwroot/mysite/wwwroot.log:
Error at restrictedobjects/code/extensions/Restrictable.php line 305: Uncaught PermissionDeniedException: You must have write permission to SiteConfig #0 (Write) (http://silversocial.dev/Security/login?BackURL=%2Fdev%2Fbuild%3Fdisable_perms%3D1)

I got this message after the database was created. Any hints what's wrong?

**Comment by nyeholt** [comment]
Most likely the issue will be that you'll need to run dev/build from the command line (with disable_perms=1), which is currently the only way to trigger the first dev/build on a site with the restrictedobjects module. 

Having said that - this project hasn't been updated for a couple of years now, so I wouldn't use it in a production setting at all. The upside to that though is that there has been quite a few updates in the past few weeks to the underlying modules (in particular the microblog module) which I'll be putting another demo system together for (which will most likely replace this repository).

**Comment by nglasl** [comment]
This project has been superceded by the ba-sis module, and is no longer maintained.

https://github.com/silverstripe-australia/silverstripe-ba-sis
